### ISSUE TITLE
Could there be a clearer indication of Public Domain or some other license?

### ISSUE THREAD

**Issue by kevinkjt2000** [brianwatling/redispp#10]
The Open Source Initiative (OSI) does not recommend this method of licensing software.  See https://opensource.org/faq#public-domain.

Wikipedia has this article on Public-domain software.  Of particular interest is the following: 

> Under the Berne Convention, which most countries have signed, an author automatically obtains the exclusive copyright to anything they have written, and local law may similarly grant copyright, patent, or trademark rights by default. The Berne Convention also covers programs. Therefore, a program is automatically subject to a copyright, and if it is to be placed in the public domain, the author must explicitly disclaim the copyright and other rights on it in some way, e.g. by a waiver statement.[1] In some Jurisdictions, some rights (in particular moral rights) cannot be disclaimed: for instance, civil law tradition-based German law's "Urheberrecht" differs here from the Anglo-Saxon common law tradition's "copyright" concept.

So this non-license method of placing software into the public domain is a bit problematical, since in order to actually place it in the public domain there should have been a waiver statement disclaiming the copyright and other rights in the software.

Any thoughts on this?  Have licenses such as Apache or CC3.0 been considered in the past?

**Comment by brianwatling** [comment]
I'm happy to accept a pull request adding a better license
