### ISSUE TITLE
Causes app to crash when a get is executed on a list.

### ISSUE THREAD

**Issue by mbejda** [brianwatling/redispp#9]
Causes app to crash when a get is executed on a list.

<pre>
    std::string keyStd = key.toUtf8().constData();
    std::string valueStd = value.toUtf8().constData();
    this->conn->lpush(keyStd, valueStd);
this->conn->get(keyStd)
</pre>

abort 6.

**Comment by kevinkjt2000** [comment]
Redis will do this because the LIST type does not match with the GET command.  Here is an interaction with the default redis-cli:
```
redis:6379> lpush "hello" "world"
(integer) 1
redis:6379> get "hello"
(error) WRONGTYPE Operation against a key holding the wrong kind of value
```
If you would like to get values from the list use LPOP or LRANGE commands instead.  https://redis.io/commands/lrange

**Comment by kevinkjt2000** [comment]
Closing this, since it seems to be intentional behavior in Redis.
